import { Title } from '@angular/platform-browser';

export interface Cliente {
  id?: number,
  Name?: string,
  LastName?: string,
  BirthDate?: Date,
  Job?: string,
  Direction?: string,
  Phone?: string,
  Gender?: string,
  CivilStatus?: string,
  DocumentNumber?: string,
  Email?: string,
  Password?: string,
  Photo?: string,
  Google?: string,
  Condition?: string,
  Code?: string,
  G?: string,
  P?: string,
  A?: string,
  C?: string,
  Fum?: Date,
  Papsmear?: string,
  Bloodtype?: string,
  Others?: string,
  Othershereditary?: string,
  Otherspathological?: string,
  Medicine?: string,
}
