import { Title } from '@angular/platform-browser';

export interface ListDetalleCita {
  id?: number,
  Othersduration?: string,
  Startdate?: Date,
  Frequency?: string,
  Datethatbecameimportant?: Date,
  Perday?: string,
  Perweek?: string,
  Permonth?: string,
  Byyear?: string,
  One?: boolean,
  Two?: boolean,
  Three?: boolean,
  Multiple?: boolean,
  Unilateral?: boolean,
  Bilateral?: boolean,
  Symmetrical?: boolean,
  Referred?: boolean,
  Irradiated?: boolean,
  Worsened?: boolean,
  Parked?: boolean,
  Decreasing?: boolean,
  Scale?: string,
  Datescale?: Date,
  Oncological?: boolean,
  Oncologicaltype?: string,
  AssociatedwithDiagnosis?: boolean,
  AssociatedwithTreatment?: boolean,
  AssociatedwithProgressiveCancer?: boolean,
  Addictions?: boolean,
  Dying?: boolean,
  Treatment?: string,
  Observations?: string,
  Protocol?: boolean,
  Protocoltype?: string,
  CitaId?: number
}
