import { Title } from '@angular/platform-browser';

export interface ListDermatomaFrontal {
  id?: number,
  DFC1?: boolean,
  DFC21?: boolean,
  DFC22?: boolean,
  DFC3?: boolean,
  DFC4?: boolean,
  DFC51?: boolean,
  DFC52?: boolean,
  DFC61?: boolean,
  DFC62?: boolean,
  DFC71?: boolean,
  DFC72?: boolean,
  DFC81?: boolean,
  DFC82?: boolean,
  DFD101?: boolean,
  DFD102?: boolean,
  DFD103?: boolean,
  DFD2?: boolean,
  DFD3?: boolean,
  DFD4?: boolean,
  DFD5?: boolean,
  DFD6?: boolean,
  DFD7?: boolean,
  DFD8?: boolean,
  DFD9?: boolean,
  DFD10?: boolean,
  DFD11?: boolean,
  DFD12?: boolean,
  DFL1?: boolean,
  DFL21?: boolean,
  DFL22?: boolean,
  DFL31?: boolean,
  DFL32?: boolean,
  DFL41?: boolean,
  DFL42?: boolean,
  DFL51?: boolean,
  DFL52?: boolean,
  DFS11?: boolean,
  DFS12?: boolean,
  DFS2?: boolean,
  DFS3?: boolean,
  CitaId?: number
}
