import { Title } from '@angular/platform-browser';

export interface ListCita {
  id?: number,
  Appointment?: Date,
  Reason?: string,
  Amount?: string,
  Pay?: string,
  Paymentstatus?: string,
  Type?: string,
  Condition?: string,
  Referred?: string,
  Companion?: string,
  Relationship?: string,
  BloodPressure?: string,
  HeartRate?: string,
  BreathingFrequency?: string,
  Temperature?: string,
  Saturation?: string,
  SickTime?: string,
  CurrentEpisode?: string,
  StartWay?: string,
  SignsandSymptoms?: string,
  DescriptionProblem?: string,
  SurgicalHistory?: string,
  MedicalHistory?: string,
  AllergicHistory?: string,
  PhysicalExam?: string,
  Diagnosis?: string,
  LaboratoryExam?: string,
  Creatininevalue?: string,
  Urea?: string,
  ETS?: boolean,
  Specifyothers?: string,
  Labamount?: string,
  Labpay?: string,
  Labpaymentstatus?: string,
  Labstatus?: string,
  Labreceptiondate?: Date,
  Labresultdate?: Date,
  AdminId?: number,
  ClienteId?: number,
  HorarioId?: number
}
